import { StudentMasterRecord, StudentAchievement, SMAMajorRecommendation, UserProfile, ServerAuditLog } from '../types';

export const DEFAULT_USERS: UserProfile[] = [
  {
    id: 'usr-root-master',
    username: 'server_utama',
    name: 'Master Server Administrator (Root)',
    email: 'root.admin@server-pusat.kemdikbud.go.id',
    role: 'superadmin',
    roleLabel: 'Akun Server Utama (Root Administrator)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    institutionName: 'Pusat Server & Database Nasional AI Studio',
    joinedDate: '2020-01-01',
    canReviewAllAccounts: true,
    canDeleteRecords: true,
    canPurgeAllDatabase: true,
    badgeColor: 'bg-rose-900 text-white ring-rose-500',
    description: 'Otoritas tertinggi server. Dapat meninjau semua akun lembaga, menghapus data individual, dan melakukan Reset / Hapus Seluruh Database.',
  },
  {
    id: 'usr-kurikulum',
    username: 'kurikulum_pusat',
    name: 'Dr. Hendra Wijaya, M.Ed. (Pengembang Kurikulum)',
    email: 'hendra.kurikulum@kemdikbud.go.id',
    role: 'kurikulum',
    roleLabel: 'Pengembang Kurikulum & Diferensiasi Pembelajaran',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    institutionName: 'Pusat Kurikulum & Pembelajaran Nasional',
    joinedDate: '2021-04-10',
    canReviewAllAccounts: true,
    canDeleteRecords: true,
    canPurgeAllDatabase: false,
    badgeColor: 'bg-blue-900 text-white ring-blue-500',
    description: 'Akun Server Spesialis. Berhak meninjau seluruh data akun lain, profil pedagogis, diferensiasi konten/proses, serta menghapus data siswa yang tidak valid.',
  },
  {
    id: 'usr-psikolog',
    username: 'psikolog_klinis',
    name: 'Dra. Anindya Larasati, M.Psi., Psikolog',
    email: 'anindya.psikolog@klinik-tumbuh.org',
    role: 'psikolog',
    roleLabel: 'Psikolog Perkembangan & Konselor Neuropsikologi',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    institutionName: 'Lembaga Psikologi & Tumbuh Kembang Anak',
    joinedDate: '2021-06-15',
    canReviewAllAccounts: true,
    canDeleteRecords: true,
    canPurgeAllDatabase: false,
    badgeColor: 'bg-purple-900 text-white ring-purple-500',
    description: 'Akun Server Spesialis. Berhak meninjau asesmen neuropsikologi, profil bakat majemuk lintas akun, konseling anak, serta menghapus data yang tidak sesuai prosedur.',
  },
  {
    id: 'usr-peneliti',
    username: 'peneliti_riset',
    name: 'Prof. Dr. Irwan Susanto, M.Sc., Ph.D.',
    email: 'irwan.peneliti@pusat-riset.edu',
    role: 'peneliti',
    roleLabel: 'Peneliti Pendidikan & Neuropsikologi Anak',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    institutionName: 'Pusat Riset Neurosains Kognitif & Pendidikan',
    joinedDate: '2021-02-20',
    canReviewAllAccounts: true,
    canDeleteRecords: true,
    canPurgeAllDatabase: false,
    badgeColor: 'bg-teal-900 text-white ring-teal-500',
    description: 'Akun Server Spesialis. Berhak meninjau dataset multi-lembaga, metrik riset perkembangan, ekspor analitik agregat, serta mengelola/menghapus data riset.',
  },
  {
    id: 'usr-lembaga-1',
    username: 'lembaga_sekolah',
    name: 'Yayasan Perguruan Cendekia Nusantara',
    email: 'admin@cendekia-school.sch.id',
    role: 'lembaga',
    roleLabel: 'Lembaga Pendidikan (Maks. 3 Anak)',
    avatar: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=150&auto=format&fit=crop&q=80',
    institutionName: 'Sekolah Inklusif Cendekia Nusantara',
    joinedDate: '2023-01-15',
    studentLimit: 3,
    canReviewAllAccounts: false,
    canDeleteRecords: false,
    canPurgeAllDatabase: false,
    badgeColor: 'bg-amber-800 text-white ring-amber-500',
    description: 'Akun Lembaga Pendidikan Mandiri. Memiliki batasan kuota ketat: Hanya dapat menginput dan meninjau maksimal 3 siswa terdaftar.',
  },
  {
    id: 'usr-guru-1',
    username: 'guru_sri',
    name: 'Dra. Sri Wahyuni, M.Pd.',
    email: 'sri.wahyuni@sekolah.sch.id',
    role: 'guru',
    roleLabel: 'Guru Kelas / Pengajar',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    institutionName: 'SMA Negeri 1 Prestasi Nusantara',
    joinedDate: '2022-03-15',
    studentLimit: 3,
    canReviewAllAccounts: false,
    canDeleteRecords: false,
    canPurgeAllDatabase: false,
    badgeColor: 'bg-emerald-800 text-white',
    description: 'Guru pengajar kelas dengan akses observasi dan input siswa.',
  },
];

export const INITIAL_AUDIT_LOGS: ServerAuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-08-20 10:15:30',
    actorId: 'usr-root-master',
    actorName: 'Master Server Administrator (Root)',
    actorRole: 'superadmin',
    actionType: 'EXPORT_DATA',
    targetDetails: 'Ekspor berkas cadangan database komprehensif (JSON Schema v3.2)',
    status: 'SUCCESS',
  },
  {
    id: 'log-2',
    timestamp: '2026-08-20 09:30:12',
    actorId: 'usr-kurikulum',
    actorName: 'Dr. Hendra Wijaya, M.Ed.',
    actorRole: 'kurikulum',
    actionType: 'UPDATE_STUDENT',
    targetDetails: 'Verifikasi pemetaan diferensiasi kurikulum Fase E untuk Siswa Muhammad Farhan',
    status: 'SUCCESS',
  },
  {
    id: 'log-3',
    timestamp: '2026-08-19 16:45:00',
    actorId: 'usr-psikolog',
    actorName: 'Dra. Anindya Larasati, M.Psi.',
    actorRole: 'psikolog',
    actionType: 'UPDATE_STUDENT',
    targetDetails: 'Penyelarasan catatan regulasi sensori proprioseptif pada siswa TK Kenzo',
    status: 'SUCCESS',
  },
];

export const INITIAL_STUDENTS: StudentMasterRecord[] = [
  {
    id: 'std-sma-1',
    nisn: '0067823910',
    fullName: 'Muhammad Farhan Al-Ghifari',
    nickname: 'Farhan',
    educationLevel: 'SMA',
    gradeClass: 'XII IPA 1',
    gender: 'Laki-laki',
    birthDate: '2008-04-12',
    ageYears: 17,
    ageMonths: 4,
    parentName: 'H. Hendra Al-Ghifari',
    parentPhone: '081234567890',
    address: 'Jl. Merdeka No. 45, Jakarta Selatan',
    specialNotes: 'Daya analisis logika dan algoritma sangat menonjol. Aktif di ekstrakurikuler Olimpiade Sains Informatika dan Robotika.',
    createdAt: '2024-07-10',
    totalAchievements: 4,
    hasObservation: true,
  },
  {
    id: 'std-sma-2',
    nisn: '0071298453',
    fullName: 'Aisyah Putri Maharani',
    nickname: 'Aisyah',
    educationLevel: 'SMA',
    gradeClass: 'XI IPS 2',
    gender: 'Perempuan',
    birthDate: '2009-08-25',
    ageYears: 16,
    ageMonths: 0,
    parentName: 'Dra. Yuni Astuti',
    parentPhone: '081398765432',
    address: 'Jl. Cendrawasih No. 12, Bandung',
    specialNotes: 'Kemampuan komunikasi publik, diplomasi, dan debat bahasa Inggris sangat fasih. Tertarik dengan isu geopolitik dan hukum internasional.',
    createdAt: '2024-07-12',
    totalAchievements: 3,
    hasObservation: true,
  },
  {
    id: 'std-sma-3',
    nisn: '0069812347',
    fullName: 'Raden Bima Satria Pratama',
    nickname: 'Bima',
    educationLevel: 'SMA',
    gradeClass: 'XII IPA 3',
    gender: 'Laki-laki',
    birthDate: '2008-02-18',
    ageYears: 17,
    ageMonths: 6,
    parentName: 'Ir. Agus Pratama',
    parentPhone: '081122334455',
    address: 'Komplek Duta Graha Blok B4, Surabaya',
    specialNotes: 'Bakat luar biasa di bidang desain 3D, arsitektur, dan ilustrasi digital. Gaya berpikir visual-spasial tingkat tinggi.',
    createdAt: '2024-07-15',
    totalAchievements: 3,
    hasObservation: true,
  },
  {
    id: 'std-sma-4',
    nisn: '0075543219',
    fullName: 'Clarissa Amanda Nadine',
    nickname: 'Amanda',
    educationLevel: 'SMA',
    gradeClass: 'X-1',
    gender: 'Perempuan',
    birthDate: '2010-05-30',
    ageYears: 15,
    ageMonths: 3,
    parentName: 'Dr. Gunawan Wibisono, Sp.A',
    parentPhone: '081567890123',
    address: 'Jl. Diponegoro No. 88, Semarang',
    specialNotes: 'Tertarik mendalam pada biologi molekuler, kedokteran umum, dan penelitian laboratorium bioteknologi.',
    createdAt: '2024-07-18',
    totalAchievements: 2,
    hasObservation: false,
  },
  {
    id: 'std-smp-1',
    nisn: '0098765432',
    fullName: 'Rafiandra Dwi Cahyo',
    nickname: 'Rafi',
    educationLevel: 'SMP',
    gradeClass: 'VIII B',
    gender: 'Laki-laki',
    birthDate: '2011-10-14',
    ageYears: 13,
    ageMonths: 10,
    parentName: 'Bambang Sudarsono',
    parentPhone: '081789012345',
    address: 'Jl. Flamboyan No. 20, Yogyakarta',
    specialNotes: 'Unggul di matematika terapan dan olahraga bulu tangkis tingkat kota.',
    createdAt: '2024-07-20',
    totalAchievements: 2,
    hasObservation: false,
  },
  {
    id: 'std-sd-1',
    nisn: '0123456789',
    fullName: 'Kinan Salsabila Ramadhani',
    nickname: 'Kinan',
    educationLevel: 'SD',
    gradeClass: 'Kelas 2A',
    gender: 'Perempuan',
    birthDate: '2018-03-22',
    ageYears: 7,
    ageMonths: 5,
    parentName: 'Indah Kusuma',
    parentPhone: '081298761234',
    address: 'Jl. Melati Indah No. 5, Malang',
    specialNotes: 'Gaya belajar visual-spasial, sedang melatih koordinasi motorik halus (dispraksia ringan).',
    createdAt: '2024-07-22',
    totalAchievements: 1,
    hasObservation: true,
  },
  {
    id: 'std-paud-1',
    nisn: '0198761234',
    fullName: 'Arga Narendra Wijaya',
    nickname: 'Arga',
    educationLevel: 'PAUD',
    gradeClass: 'TK B Ceria',
    gender: 'Laki-laki',
    birthDate: '2020-11-05',
    ageYears: 4,
    ageMonths: 9,
    parentName: 'Danang Wijaya',
    parentPhone: '081345678901',
    address: 'Jl. Kenanga Asri No. 17, Surakarta',
    specialNotes: 'Pembelajar kinestetik aktif dengan regulasi sensori proprioseptif.',
    createdAt: '2024-07-25',
    totalAchievements: 1,
    hasObservation: true,
  },
];

export const INITIAL_ACHIEVEMENTS: StudentAchievement[] = [
  {
    id: 'ach-1',
    studentId: 'std-sma-1',
    studentName: 'Muhammad Farhan Al-Ghifari',
    educationLevel: 'SMA',
    gradeClass: 'XII IPA 1',
    title: 'Juara 1 Olimpiade Sains Nasional (OSN) Bidang Informatika',
    category: 'Akademik / Sains',
    level: 'Nasional',
    rank: 'Juara 1 (Medali Emas)',
    year: '2025',
    organizer: 'Pusat Prestasi Nasional (Puspresnas) Kemendikbudristek',
    description: 'Menyelesaikan 4 soal algoritma pemrograman kompetitif dan struktur data tingkat lanjut dengan skor tertinggi.',
    certificateUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    dateRecorded: '2025-09-15',
  },
  {
    id: 'ach-2',
    studentId: 'std-sma-1',
    studentName: 'Muhammad Farhan Al-Ghifari',
    educationLevel: 'SMA',
    gradeClass: 'XII IPA 1',
    title: 'Juara 2 National Youth AI & Robotics Hackathon',
    category: 'Teknologi & Robotika',
    level: 'Nasional',
    rank: 'Juara 2 (Silver Award)',
    year: '2025',
    organizer: 'Institut Teknologi Bandung & IEEE Student Branch',
    description: 'Mengembangkan prototipe sistem pendeteksi kepatuhan lalu lintas berbasis Computer Vision AI.',
    certificateUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600&auto=format&fit=crop&q=80',
    dateRecorded: '2025-11-20',
  },
  {
    id: 'ach-3',
    studentId: 'std-sma-1',
    studentName: 'Muhammad Farhan Al-Ghifari',
    educationLevel: 'SMA',
    gradeClass: 'XII IPA 1',
    title: 'Top 10 Finalist International Bebras Computational Thinking Challenge',
    category: 'Akademik / Sains',
    level: 'Internasional',
    rank: 'Top 10 Finalist',
    year: '2024',
    organizer: 'Bebras International Community',
    description: 'Menunjukkan kemampuan computational thinking dan dekomposisi logika matematika.',
    dateRecorded: '2024-12-05',
  },
  {
    id: 'ach-4',
    studentId: 'std-sma-2',
    studentName: 'Aisyah Putri Maharani',
    educationLevel: 'SMA',
    gradeClass: 'XI IPS 2',
    title: 'Best Delegate & Best Position Paper di Indonesia Model United Nations (IMUN)',
    category: 'Kepemimpinan & Organisasi',
    level: 'Nasional',
    rank: 'Best Delegate (Juara 1)',
    year: '2025',
    organizer: 'Universitas Indonesia MUN Club',
    description: 'Mewakili dewan UNESCO dalam merumuskan resolusi perlindungan warisan budaya dan hak pendidikan global.',
    certificateUrl: 'https://images.unsplash.com/photo-1544531586-fde5298cdd40?w=600&auto=format&fit=crop&q=80',
    dateRecorded: '2025-10-18',
  },
  {
    id: 'ach-5',
    studentId: 'std-sma-2',
    studentName: 'Aisyah Putri Maharani',
    educationLevel: 'SMA',
    gradeClass: 'XI IPS 2',
    title: 'Juara 1 Lomba Debat Bahasa Inggris National High School Championship',
    category: 'Akademik / Sains',
    level: 'Provinsi',
    rank: 'Juara 1 & Best Speaker',
    year: '2025',
    organizer: 'Dinas Pendidikan Provinsi Jawa Barat',
    description: 'Meraih skor pembicara tertinggi dalam mosi kebijakan ekonomi sirkular dan transisi energi hijau.',
    dateRecorded: '2025-08-30',
  },
  {
    id: 'ach-6',
    studentId: 'std-sma-3',
    studentName: 'Raden Bima Satria Pratama',
    educationLevel: 'SMA',
    gradeClass: 'XII IPA 3',
    title: 'Juara 1 Festival Arsitektur Muda & Desain Maket Berkelanjutan',
    category: 'Seni & Budaya',
    level: 'Provinsi',
    rank: 'Juara 1 (Gold Trophy)',
    year: '2025',
    organizer: 'Ikatan Arsitek Indonesia (IAI) Jawa Timur',
    description: 'Merancang model rumah ramah lingkungan dengan sistem ventilasi alami dan panel surya terintegrasi.',
    certificateUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    dateRecorded: '2025-09-28',
  },
  {
    id: 'ach-7',
    studentId: 'std-smp-1',
    studentName: 'Rafiandra Dwi Cahyo',
    educationLevel: 'SMP',
    gradeClass: 'VIII B',
    title: 'Juara 1 Kejuaraan Bulu Tangkis Pelajar Tingkat Kota (O2SN SMP)',
    category: 'Olahraga',
    level: 'Kota/Kabupaten',
    rank: 'Juara 1 (Medali Emas)',
    year: '2025',
    organizer: 'BAPOPSI & Dinas Pemuda dan Olahraga',
    description: 'Kategori Tunggal Putra Bulu Tangkis dengan performa tanpa kekalahan sepanjang turnamen.',
    dateRecorded: '2025-06-12',
  },
  {
    id: 'ach-8',
    studentId: 'std-sd-1',
    studentName: 'Kinan Salsabila Ramadhani',
    educationLevel: 'SD',
    gradeClass: 'Kelas 2A',
    title: 'Juara Harapan 1 Lomba Mewarnai & Gambar Cerita Anak Bertema Cinta Lingkungan',
    category: 'Seni & Budaya',
    level: 'Kecamatan',
    rank: 'Juara Harapan 1',
    year: '2024',
    organizer: 'Pusat Kreativitas Anak Mandiri',
    description: 'Karya gambar cerita dengan gradasi warna krayon dan imajinasi visual flora fauna.',
    dateRecorded: '2024-11-10',
  },
];

export const INITIAL_SMA_RECOMMENDATIONS: Record<string, SMAMajorRecommendation> = {
  'std-sma-1': {
    id: 'rec-sma-1',
    studentId: 'std-sma-1',
    studentName: 'Muhammad Farhan Al-Ghifari',
    gradeClass: 'XII IPA 1',
    primaryInterests: ['Teknologi Informasi & Kecerdasan Buatan (AI)', 'Pemrograman & Algoritma', 'Robotika & Rekayasa Perangkat Lunak'],
    favoriteSubjects: ['Matematika Lanjut', 'Informatika / Koding', 'Fisika'],
    hobbiesAndPassion: ['Pemrograman Python & C++', 'Membuat Bot Otomasi', 'Bermain Catur & Memecahkan Teka-Teki Logika'],
    careerAspirations: 'AI Research Scientist / Principal Software Architect di perusahaan teknologi global atau mendirikan tech startup.',
    learningStyleSynergy: 'Pemrosesan logika analitis, dekomposisi masalah sekuensial, dan fokus mendalam (deep work) pada pemecahan sistematis.',
    topRecommendedMajors: [
      {
        majorName: 'Ilmu Komputer / Teknik Informatika (Computer Science)',
        faculty: 'Fakultas Ilmu Komputer / Fakultas Teknologi Informasi',
        matchScore: 98,
        cognitiveAlignmentReason: 'Gaya berpikir logis-algoritmik dan rekam jejak OSN Informatika selaras 100% dengan kurikulum struktur data, machine learning, dan arsitektur komputasi tinggi.',
        potentialCareers: ['AI & Machine Learning Engineer', 'Software Architect', 'Data Scientist', 'CTO / Tech Founder'],
        recommendedSubjectsToStrengthen: ['Kalkulus & Aljabar Linier', 'Struktur Data & Algoritma', 'Bahasa Inggris Akademik'],
        topUniversitiesInIndonesia: ['Institut Teknologi Bandung (ITB)', 'Universitas Indonesia (UI)', 'Institut Teknologi Sepuluh Nopember (ITS)', 'Universitas Gadjah Mada (UGM)'],
      },
      {
        majorName: 'Teknik Elektro / Rekayasa Perangkat Keras (Electrical & Robotics Engineering)',
        faculty: 'Fakultas Teknik Industri / Teknik Elektro',
        matchScore: 92,
        cognitiveAlignmentReason: 'Ketertarikan pada robotika dan hardware automation melengkapi kekuatan analisis matematika terapan dan sistem tertanam (embedded systems).',
        potentialCareers: ['Robotics Engineer', 'IoT Solutions Architect', 'Hardware Design Specialist'],
        recommendedSubjectsToStrengthen: ['Fisika Listrik & Magnet', 'Sensor & Mikroelektronika'],
        topUniversitiesInIndonesia: ['ITB', 'ITS', 'UI', 'UGM'],
      },
      {
        majorName: 'Sains Data & Matematika Terapan (Data Science & Actuarial Math)',
        faculty: 'Fakultas Matematika dan Ilmu Pengetahuan Alam (FMIPA)',
        matchScore: 89,
        cognitiveAlignmentReason: 'Kemampuan inferensi statistik dan kecakapan komputasi memungkinkan pemodelan prediksi skala besar yang sangat dibutuhkan di era big data.',
        potentialCareers: ['Lead Data Analyst', 'Quantitative Researcher', 'Algorithmic Financial Strategist'],
        recommendedSubjectsToStrengthen: ['Teori Peluang & Statistik Terapan', 'Pemrograman R & Python'],
        topUniversitiesInIndonesia: ['Universitas Airlangga (UNAIR)', 'IPB University', 'UI', 'UGM'],
      },
    ],
    actionPlanForSMA: [
      'Memperkuat portofolio GitHub proyek AI/Machine Learning untuk pendaftaran jalur prestasi/portofolio PTN/PTS.',
      'Mengikuti kompetisi koding perguruan tinggi (misal: Gemastik/CP Internasional) tingkat pelajar.',
      'Mempersiapkan tes SNBT/UTBK pada subtes Penalaran Matematika dan Literasi Bahasa Inggris.',
    ],
    generatedAt: '2026-08-20T10:30:00.000Z',
  },
};
